### ISSUE TITLE
jdk version not match error

### ISSUE THREAD

**Issue by DavyJones2010** [jenkinsci/alibabacloud-ecs-plugin#24]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

CentOS 7

### Reproduction steps

Provision nodes as https://plugins.jenkins.io/alibabacloud-ecs/ doc instructed.

### Expected Results

successful launch jenkins agents on worker nodes.

### Actual Results

ERROR: Unable to launch the agent for cn-qingdao-c-ecs.mn4.large-i-m5eehp117mqdq0i877zx
java.lang.UnsupportedClassVersionError: hudson/slaves/SlaveComputer$SlaveVersion has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:635)
	at hudson.remoting.RemoteClassLoader.loadClassFile(RemoteClassLoader.java:458)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to cn-qingdao-c-ecs.mn4.large-i-m5eehp117mqdq0i877zx
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1000)
		at hudson.slaves.SlaveComputer.setChannel(SlaveComputer.java:660)
		at hudson.slaves.SlaveComputer.setChannel(SlaveComputer.java:438)
		at hudson.slaves.CommandLauncher.launch(CommandLauncher.java:170)
		at com.alibabacloud.jenkins.ecs.AlibabaEcsUnixComputerLauncher.launchScript(AlibabaEcsUnixComputerLauncher.java:90)
		at com.alibabacloud.jenkins.ecs.AlibabaEcsComputerLauncher.launch(AlibabaEcsComputerLauncher.java:13)
		at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:298)
		at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:48)
		at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:82)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at java.base/java.lang.Thread.run(Thread.java:829)
Caused: java.lang.UnsupportedClassVersionError: Failed to load hudson.slaves.SlaveComputer$SlaveVersion
	at hudson.remoting.RemoteClassLoader.loadClassFile(RemoteClassLoader.java:460)
	at hudson.remoting.RemoteClassLoader.loadRemoteClass(RemoteClassLoader.java:292)
	at hudson.remoting.RemoteClassLoader.loadWithMultiClassLoader(RemoteClassLoader.java:269)
	at hudson.remoting.RemoteClassLoader.findClass(RemoteClassLoader.java:228)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at hudson.remoting.MultiClassLoaderSerializer$Input.resolveClass(MultiClassLoaderSerializer.java:132)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1987)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1851)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2185)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1668)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:502)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:460)
	at hudson.remoting.UserRequest.deserialize(UserRequest.java:289)
	at hudson.remoting.UserRequest.perform(UserRequest.java:189)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:376)
	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by DavyJones2010** [comment]
fixed. see https://github.com/jenkinsci/alibabacloud-ecs-plugin/pull/40
